from pathlib import Path

p = Path(__file__).with_name("dashboard.html")
s = p.read_text(encoding="utf-8")
MARK = "UGAFORCE_UI_UPGRADE_V1"
if MARK in s:
    raise SystemExit(0)

css = r'''
<style id="UGAFORCE_UI_UPGRADE_V1">
.nav [data-view="people"]{color:#5aa2ff}.nav [data-view="recruiting"]{color:#b07cff}.nav [data-view="onboarding"]{color:#43c58a}.nav [data-view="time"]{color:#39bdd0}.nav [data-view="payroll"]{color:#65bf69}.nav [data-view="performance"]{color:#e0a82e}.nav [data-view="approvals"]{color:#7c83ff}.nav [data-view="analytics"]{color:#a65ee6}.nav [data-view="admin"]{color:#9eacb8}
.hr-module-color{font-weight:800}.hr-color-people{color:#246fd6!important}.hr-color-recruiting{color:#7a3fc0!important}.hr-color-onboarding{color:#16875a!important}.hr-color-time{color:#087f91!important}.hr-color-payroll{color:#287a37!important}.hr-color-performance{color:#a86d00!important}.hr-color-approvals{color:#4b55c9!important}.hr-color-analytics{color:#7a39aa!important}.hr-color-admin{color:#465563!important}
.recruit-actions{margin:16px 0;padding:16px;border:1px solid #ddd6f0;border-left:5px solid #7a3fc0;border-radius:14px;background:linear-gradient(135deg,#fff,#faf7ff)}.recruit-actions h2{margin:0 0 4px;font-size:18px;color:#6c35ae}.recruit-actions p{margin:0 0 14px;color:#6e7882;font-size:12px}.recruit-actions .row{display:flex;gap:8px;flex-wrap:wrap}.recruit-actions button{border:0;border-radius:10px;padding:10px 13px;font-weight:750;background:#6f38b1;color:#fff}.recruit-actions button.secondary{background:#eef1f4;color:#263844}.ops-block{margin-top:15px}.ops-block h3{margin:0 0 8px;font-size:14px}.ops-list{display:grid;gap:8px}.ops-item{border:1px solid #e2e6ea;border-radius:11px;padding:11px;background:white;display:flex;justify-content:space-between;gap:10px;align-items:center}.ops-item small{display:block;color:#74808a;margin-top:3px}.ops-item button{padding:7px 10px;font-size:12px}.hr-modal{position:fixed;inset:0;background:rgba(10,18,24,.55);z-index:10000;display:grid;place-items:center;padding:18px}.hr-modal.hidden{display:none!important}.hr-dialog{width:min(100%,560px);max-height:90vh;overflow:auto;background:#fff;border-radius:18px;padding:20px;box-shadow:0 24px 70px rgba(0,0,0,.28)}.hr-dialog h2{margin:0 0 14px}.hr-form{display:grid;gap:10px}.hr-form input,.hr-form select,.hr-form textarea{width:100%;border:1px solid #d8e0e5;border-radius:10px;padding:11px;font:inherit}.hr-form textarea{min-height:90px}.hr-form .actions{display:flex;gap:8px;justify-content:flex-end;margin-top:6px}.hr-form button{border:0;border-radius:9px;padding:10px 13px;font-weight:750}.hr-form .save{background:#172936;color:white}.hr-msg{font-size:12px;color:#a0333d;min-height:16px}
</style>
'''

js = r'''
<script>
(()=>{
const roleCanEdit=()=>currentUser&&['HR_SPECIALIST','HR_MANAGER','HR_ADMIN'].includes(currentUser.role);
const roleCanApprove=()=>currentUser&&['HR_MANAGER','HR_ADMIN'].includes(currentUser.role);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function colorModules(){
 const colors={people:'people',recruiting:'recruiting',onboarding:'onboarding','time & attendance':'time','payroll & benefits':'payroll',performance:'performance',approvals:'approvals',analytics:'analytics',administration:'admin'};
 document.querySelectorAll('button,div,strong,h2,h3').forEach(el=>{const t=(el.textContent||'').trim().toLowerCase();if(colors[t])el.classList.add('hr-module-color','hr-color-'+colors[t]);});
}
function modal(title,body,onSave){let m=document.getElementById('hrOpsModal');if(!m){m=document.createElement('div');m.id='hrOpsModal';m.className='hr-modal hidden';m.innerHTML='<div class="hr-dialog"><h2 id="hrModalTitle"></h2><form id="hrModalForm" class="hr-form"><div id="hrModalBody"></div><div class="hr-msg" id="hrModalMsg"></div><div class="actions"><button type="button" id="hrModalCancel">Cancel</button><button class="save" type="submit">Save</button></div></form></div>';document.body.appendChild(m);hrModalCancel.onclick=()=>m.classList.add('hidden');}
 hrModalTitle.textContent=title;hrModalBody.innerHTML=body;hrModalMsg.textContent='';m.classList.remove('hidden');hrModalForm.onsubmit=async e=>{e.preventDefault();try{await onSave(new FormData(hrModalForm));m.classList.add('hidden');await loadRecruitOps();await loadRecruiting();}catch(err){hrModalMsg.textContent=err.message||String(err)}};
}
async function options(){const [d,e]=await Promise.all([req('/departments'),req('/employees?status=active&limit=200')]);return {deps:d.results||[],emps:e.results||[]}}
async function createReq(){const o=await options();modal('Create requisition',`<input name="title" placeholder="Job title" required><select name="department_id"><option value="">Department (optional)</option>${o.deps.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')}</select><select name="hiring_manager_id" required><option value="">Hiring manager</option>${o.emps.map(x=>`<option value="${esc(x.id)}">${esc(x.first_name)} ${esc(x.last_name)} — ${esc(x.job_title||'')}</option>`).join('')}</select><input name="headcount" type="number" min="1" max="500" value="1" required><select name="employment_type"><option value="full_time">Full time</option><option value="part_time">Part time</option><option value="contract">Contract</option><option value="temporary">Temporary</option></select><input name="target_pay_min" type="number" step="0.01" placeholder="Target pay minimum"><input name="target_pay_max" type="number" step="0.01" placeholder="Target pay maximum"><textarea name="justification" placeholder="Business justification"></textarea>`,async f=>{const b={title:f.get('title'),department_id:f.get('department_id')||null,hiring_manager_id:f.get('hiring_manager_id'),headcount:Number(f.get('headcount')||1),employment_type:f.get('employment_type'),target_pay_min:f.get('target_pay_min')?Number(f.get('target_pay_min')):null,target_pay_max:f.get('target_pay_max')?Number(f.get('target_pay_max')):null,justification:f.get('justification')||null};await req('/recruiting/requisitions',{method:'POST',body:JSON.stringify(b)})})}
async function createPosting(){const r=await req('/recruiting/requisitions?status=approved');const rows=r.results||[];if(!rows.length)throw new Error('No approved requisitions are available yet.');modal('Create job posting',`<select name="requisition_id" required><option value="">Approved requisition</option>${rows.map(x=>`<option value="${esc(x.id)}">${esc(x.title)} — ${esc(x.department_name||'No department')}</option>`).join('')}</select><input name="title" placeholder="Posting title" required><textarea name="description_md" placeholder="Job description" required></textarea><input name="location" placeholder="Location"><select name="remote_policy"><option value="onsite">Onsite</option><option value="hybrid">Hybrid</option><option value="remote">Remote</option></select>`,async f=>{await req('/recruiting/postings',{method:'POST',body:JSON.stringify({requisition_id:f.get('requisition_id'),title:f.get('title'),description_md:f.get('description_md'),location:f.get('location')||null,remote_policy:f.get('remote_policy')})})})}
async function loadRecruitOps(){const sec=document.getElementById('recruiting');if(!sec)return;if(!document.getElementById('recruitOps')){const box=document.createElement('div');box.id='recruitOps';box.className='recruit-actions';box.innerHTML='<h2>Recruiting Operations</h2><p>Create, approve and publish real hiring work.</p><div class="row"><button id="newReq">Create Requisition</button><button id="newPosting">Create Job Posting</button><button class="secondary" id="refreshOps">Refresh</button></div><div class="ops-block"><h3>Requisitions</h3><div id="reqOpsList" class="ops-list"></div></div><div class="ops-block"><h3>Job Postings</h3><div id="postingOpsList" class="ops-list"></div></div>';sec.insertBefore(box,sec.firstChild);newReq.onclick=()=>createReq().catch(e=>alert(e.message));newPosting.onclick=()=>createPosting().catch(e=>alert(e.message));refreshOps.onclick=loadRecruitOps;}
 newReq.style.display=roleCanEdit()?'':'none';newPosting.style.display=roleCanEdit()?'':'none';
 const [rq,po]=await Promise.all([req('/recruiting/requisitions'),req('/recruiting/postings')]);
 reqOpsList.innerHTML=(rq.results||[]).map(x=>`<div class="ops-item"><div><b>${esc(x.title)}</b><small>${esc(x.department_name||'No department')} • ${esc(x.hiring_manager||'')} • ${esc(x.status)}</small></div>${roleCanApprove()&&['draft','pending_approval'].includes(x.status)?`<button data-approve="${esc(x.id)}">Approve</button>`:''}</div>`).join('')||'<div class="ops-item">No requisitions yet.</div>';
 postingOpsList.innerHTML=(po.results||[]).map(x=>`<div class="ops-item"><div><b>${esc(x.title)}</b><small>${esc(x.department_name||'No department')} • ${esc(x.status)} • ${esc(x.location||'')}</small></div>${roleCanEdit()&&['draft','paused'].includes(x.status)?`<button data-publish="${esc(x.id)}">Publish</button>`:''}</div>`).join('')||'<div class="ops-item">No job postings yet.</div>';
 reqOpsList.querySelectorAll('[data-approve]').forEach(b=>b.onclick=async()=>{await req('/recruiting/requisitions/'+b.dataset.approve+'/approve',{method:'POST'});await loadRecruitOps();await loadRecruiting()});
 postingOpsList.querySelectorAll('[data-publish]').forEach(b=>b.onclick=async()=>{await req('/recruiting/postings/'+b.dataset.publish+'/publish',{method:'POST'});await loadRecruitOps();await loadRecruiting()});
}
colorModules();setInterval(()=>{colorModules();const s=document.getElementById('recruiting');if(s&&!s.classList.contains('hidden')&&currentUser)loadRecruitOps().catch(()=>{})},1200);
document.addEventListener('click',e=>{const b=e.target.closest('[data-view="recruiting"]');if(b)setTimeout(()=>loadRecruitOps().catch(()=>{}),100)},true);
})();
</script>
'''

s = s.replace('</head>', css + '\n</head>', 1)
s = s.replace('</body>', js + '\n</body>', 1)
p.write_text(s, encoding='utf-8')
